server:
  address: localhost
  port: 8000
in_cluster: false
deployment:
  accessible_namespaces:
  - bookinfo
  - default
  - istio-system
external_services:
  prometheus:
    url: http://localhost:19090
  tracing:
    enabled: true
    in_cluster_url: https://jaeger-query.istio-system.svc.cluster.local
    url: https://jaeger-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com
    namespace: istio-system
    port: 443
    service : jaeger-query
    auth:
      insecure_skip_verify: true
      password: 7xyUn5hM7v1B9LYy2ojzRQJs9HAtDiUWiVGN8Yi+eGqaUYurYEDbD2ILXpwgMg/Kpfog0b6AriGPsDfOTpdhV2ocWjAKgQVKAFfZ1fFdKGSVUSxIxJhZDv43EjZN3bCZCBvqsycnCmvkLhNr+hF7RqjidQlQCAnmjKjxBfjnxSs0NkXaVQX0wJlvkhRpDHAgXWT01Onj7B7C2W0fHCIAdHAy59cAzoOb4Djq/91aNd6h9jaynBCVQ6lcYyuFXvWSU2V9ez1a7jZxh0YEVGKfVkvP01KGvwDPZOjPJX21K1bWO3NOeQfOr5ep43rI9Q2M+qOdlc1H+YCPrt4ZB/RY
      type: basic
      use_kiali_token: false
      username: internal
  grafana:
    url: https://grafana-istio-system.apps.xcanalma.devcluster.openshift.com
auth:
  strategy: anonymous
