server:
  address: localhost
  port: 8000
in_cluster: false
login_token:
  signing_key: randomgeneratedtoken
deployment:
  accessible_namespaces:
  - bookinfo
  - default
  - istio-system
external_services:
  prometheus:
    url: http://localhost:19090
  tracing:
    auth:
      ca_file: ''
      insecure_skip_verify: false
      password: ''
      token: ''
      type: none
      use_kiali_token: false
      username: ''
    enabled: true
    health_check_url: ''
    in_cluster_url: 'http://tracing.istio-system/jaeger'
    is_core: false
    namespace_selector: true
    url: 'http://localhost:16685/jaeger'
    use_grpc: true
    whitelist_istio_system:
    - jaeger-query
    - istio-ingressgateway
  grafana:
    enabled: false
    url: https://grafana-istio-system.apps.openshift.com
  istio:
    istio_identity_domain: svc.cluster.local
    istio_sidecar_annotation: sidecar.istio.io/status
    config_map_name: istio-1-9-1
    istiod_deployment_name: istiod-1-9-1
kubernetes_config:
  cache_enabled: true
auth:
  strategy: anonymous
extensions:
  threescale:
    adapter_name: threescale
    adapter_port: 3333
    adapter_service: threescale-istio-adapter
    enabled: true
    template_name: threescale-authorization
