apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: admin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - admin.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: admin-gateway
spec:
  gateways:
  - admin-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: reviews
        subset: admin
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: admin-gateway
spec:
  host: reviews
  subsets:
  - labels:
      version: v1
    name: admin
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: user-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - user.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-gateway
spec:
  gateways:
  - user-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: reviews
        subset: user
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: user-gateway
spec:
  host: reviews
  subsets:
  - labels:
      version: v2
    name: user
