apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: products-viewer
  namespace: bookinfo
spec:
  rules:
  - services: ["productpage.bookinfo.svc.cluster.local"]
    methods: ["GET", "HEAD"]

